{
   "jobs": {
      "kube-v1_27": {
         "runs-on": "ubuntu-latest",
         "steps": [
            {
               "name": "Checkout code",
               "uses": "actions/checkout@v2"
            },
            {
               "name": "Setup Docker",
               "uses": "docker/setup-buildx-action@v1"
            },
            {
               "id": "make_tests",
               "name": "Run v1.27 integration tests via docker-compose using v1.27.2-k3s1 image",
               "run": "make -C tests e2e-tests-v1.27.2-k3s1\n"
            }
         ]
      }
   },
   "name": "CI kube-v1.27",
   "on": [
      "push",
      "pull_request"
   ]
}
